# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'uidpvPby.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QGridLayout, QGroupBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QPushButton,
    QSizePolicy, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 801, 601))
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.shouye = QWidget()
        self.shouye.setObjectName(u"shouye")
        self.gridLayoutWidget = QWidget(self.shouye)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(9, 9, 781, 551))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.shouye_welcome = QLabel(self.gridLayoutWidget)
        self.shouye_welcome.setObjectName(u"shouye_welcome")
        self.shouye_welcome.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.shouye_welcome, 0, 0, 1, 1)

        self.tabWidget.addTab(self.shouye, "")
        self.dingyi = QWidget()
        self.dingyi.setObjectName(u"dingyi")
        self.groupBox_19 = QGroupBox(self.dingyi)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 10, 221, 301))
        self.dingyi_hanshuliebiao = QListWidget(self.groupBox_19)
        self.dingyi_hanshuliebiao.setObjectName(u"dingyi_hanshuliebiao")
        self.dingyi_hanshuliebiao.setGeometry(QRect(10, 20, 201, 271))
        self.groupBox_20 = QGroupBox(self.dingyi)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(250, 10, 531, 151))
        self.formLayoutWidget = QWidget(self.groupBox_20)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(10, 30, 511, 91))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(u"label_7")

        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label_7)

        self.dingyi_mingcheng = QLineEdit(self.formLayoutWidget)
        self.dingyi_mingcheng.setObjectName(u"dingyi_mingcheng")

        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.dingyi_mingcheng)

        self.label_8 = QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.label_8)

        self.dingyi_biaodashi = QLineEdit(self.formLayoutWidget)
        self.dingyi_biaodashi.setObjectName(u"dingyi_biaodashi")

        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.dingyi_biaodashi)

        self.label_9 = QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(u"label_9")

        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.label_9)

        self.dingyi_dingyiyu = QLineEdit(self.formLayoutWidget)
        self.dingyi_dingyiyu.setObjectName(u"dingyi_dingyiyu")

        self.formLayout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.dingyi_dingyiyu)

        self.dingyi_shanchu = QPushButton(self.groupBox_20)
        self.dingyi_shanchu.setObjectName(u"dingyi_shanchu")
        self.dingyi_shanchu.setGeometry(QRect(440, 120, 81, 26))
        self.dingyi_baocun = QPushButton(self.groupBox_20)
        self.dingyi_baocun.setObjectName(u"dingyi_baocun")
        self.dingyi_baocun.setGeometry(QRect(350, 120, 81, 26))
        self.label_12 = QLabel(self.groupBox_20)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 120, 84, 24))
        self.dingyi_zibianliang = QLineEdit(self.groupBox_20)
        self.dingyi_zibianliang.setObjectName(u"dingyi_zibianliang")
        self.dingyi_zibianliang.setGeometry(QRect(100, 120, 241, 24))
        self.dingyi_zibianliang.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.groupBox_21 = QGroupBox(self.dingyi)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(250, 170, 531, 141))
        self.dingyi_hanshushuxing = QComboBox(self.groupBox_21)
        self.dingyi_hanshushuxing.setObjectName(u"dingyi_hanshushuxing")
        self.dingyi_hanshushuxing.setGeometry(QRect(10, 20, 121, 20))
        self.dingyi_hanshushuxing_view = QWebEngineView(self.groupBox_21)
        self.dingyi_hanshushuxing_view.setObjectName(u"dingyi_hanshushuxing_view")
        self.dingyi_hanshushuxing_view.setGeometry(QRect(10, 50, 511, 81))
        self.dingyi_hanshushuxing_view.setUrl(QUrl(u"about:blank"))
        self.dingyi_hanshushuxing_lineedit = QLineEdit(self.groupBox_21)
        self.dingyi_hanshushuxing_lineedit.setObjectName(u"dingyi_hanshushuxing_lineedit")
        self.dingyi_hanshushuxing_lineedit.setGeometry(QRect(140, 20, 381, 21))
        self.groupBox_22 = QGroupBox(self.dingyi)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.groupBox_22.setGeometry(QRect(10, 320, 771, 241))
        self.label_11 = QLabel(self.groupBox_22)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 30, 71, 18))
        self.dingyi_zibianliangzhi = QLineEdit(self.groupBox_22)
        self.dingyi_zibianliangzhi.setObjectName(u"dingyi_zibianliangzhi")
        self.dingyi_zibianliangzhi.setGeometry(QRect(90, 30, 671, 21))
        self.dingyi_qiuzhi = QWebEngineView(self.groupBox_22)
        self.dingyi_qiuzhi.setObjectName(u"dingyi_qiuzhi")
        self.dingyi_qiuzhi.setGeometry(QRect(10, 60, 751, 141))
        self.dingyi_qiuzhi.setUrl(QUrl(u"about:blank"))
        self.dingyi_qiuzhi_lineedit = QLineEdit(self.groupBox_22)
        self.dingyi_qiuzhi_lineedit.setObjectName(u"dingyi_qiuzhi_lineedit")
        self.dingyi_qiuzhi_lineedit.setGeometry(QRect(10, 210, 751, 21))
        self.tabWidget.addTab(self.dingyi, "")
        self.qiudao = QWidget()
        self.qiudao.setObjectName(u"qiudao")
        self.groupBox1 = QGroupBox(self.qiudao)
        self.groupBox1.setObjectName(u"groupBox1")
        self.groupBox1.setGeometry(QRect(10, 10, 771, 51))
        self.qiudao_input = QLineEdit(self.groupBox1)
        self.qiudao_input.setObjectName(u"qiudao_input")
        self.qiudao_input.setGeometry(QRect(10, 20, 751, 21))
        self.groupBox2 = QGroupBox(self.qiudao)
        self.groupBox2.setObjectName(u"groupBox2")
        self.groupBox2.setGeometry(QRect(10, 110, 771, 131))
        self.qiudao_yuanhanshu = QWebEngineView(self.groupBox2)
        self.qiudao_yuanhanshu.setObjectName(u"qiudao_yuanhanshu")
        self.qiudao_yuanhanshu.setGeometry(QRect(10, 20, 751, 101))
        self.qiudao_yuanhanshu.setUrl(QUrl(u"about:blank"))
        self.groupBox3 = QGroupBox(self.qiudao)
        self.groupBox3.setObjectName(u"groupBox3")
        self.groupBox3.setGeometry(QRect(10, 250, 771, 131))
        self.qiudao_daohanshu = QWebEngineView(self.groupBox3)
        self.qiudao_daohanshu.setObjectName(u"qiudao_daohanshu")
        self.qiudao_daohanshu.setGeometry(QRect(10, 19, 751, 71))
        self.qiudao_daohanshu.setUrl(QUrl(u"about:blank"))
        self.qiudao_daohanshu_lineedit = QLineEdit(self.groupBox3)
        self.qiudao_daohanshu_lineedit.setObjectName(u"qiudao_daohanshu_lineedit")
        self.qiudao_daohanshu_lineedit.setGeometry(QRect(10, 100, 751, 21))
        self.qiudao_qiudao_button = QPushButton(self.qiudao)
        self.qiudao_qiudao_button.setObjectName(u"qiudao_qiudao_button")
        self.qiudao_qiudao_button.setGeometry(QRect(10, 530, 771, 26))
        self.groupBox = QGroupBox(self.qiudao)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 60, 121, 51))
        self.qiudao_zibianliang = QLineEdit(self.groupBox)
        self.qiudao_zibianliang.setObjectName(u"qiudao_zibianliang")
        self.qiudao_zibianliang.setGeometry(QRect(10, 20, 101, 24))
        self.qiudao_yinhanshu = QCheckBox(self.qiudao)
        self.qiudao_yinhanshu.setObjectName(u"qiudao_yinhanshu")
        self.qiudao_yinhanshu.setGeometry(QRect(530, 80, 89, 22))
        self.groupBox_3 = QGroupBox(self.qiudao)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(270, 60, 121, 51))
        self.qiudao_qiudaocishu = QLineEdit(self.groupBox_3)
        self.qiudao_qiudaocishu.setObjectName(u"qiudao_qiudaocishu")
        self.qiudao_qiudaocishu.setGeometry(QRect(10, 20, 101, 24))
        self.groupBox_4 = QGroupBox(self.qiudao)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(140, 60, 121, 51))
        self.qiudao_yinbianliang = QLineEdit(self.groupBox_4)
        self.qiudao_yinbianliang.setObjectName(u"qiudao_yinbianliang")
        self.qiudao_yinbianliang.setEnabled(False)
        self.qiudao_yinbianliang.setGeometry(QRect(10, 20, 101, 24))
        self.groupBox_5 = QGroupBox(self.qiudao)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 390, 771, 131))
        self.qiudao_daoshuzhi = QWebEngineView(self.groupBox_5)
        self.qiudao_daoshuzhi.setObjectName(u"qiudao_daoshuzhi")
        self.qiudao_daoshuzhi.setGeometry(QRect(10, 20, 751, 71))
        self.qiudao_daoshuzhi.setUrl(QUrl(u"about:blank"))
        self.qiudao_daoshuzhi_lineedit = QLineEdit(self.groupBox_5)
        self.qiudao_daoshuzhi_lineedit.setObjectName(u"qiudao_daoshuzhi_lineedit")
        self.qiudao_daoshuzhi_lineedit.setGeometry(QRect(10, 100, 751, 21))
        self.groupBox_6 = QGroupBox(self.qiudao)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(400, 60, 121, 51))
        self.qiudao_zibianliangzhi = QLineEdit(self.groupBox_6)
        self.qiudao_zibianliangzhi.setObjectName(u"qiudao_zibianliangzhi")
        self.qiudao_zibianliangzhi.setEnabled(False)
        self.qiudao_zibianliangzhi.setGeometry(QRect(10, 20, 101, 24))
        self.qiudao_qiuchujutizhi = QCheckBox(self.qiudao)
        self.qiudao_qiuchujutizhi.setObjectName(u"qiudao_qiuchujutizhi")
        self.qiudao_qiuchujutizhi.setGeometry(QRect(600, 80, 89, 22))
        self.tabWidget.addTab(self.qiudao, "")
        self.jifen = QWidget()
        self.jifen.setObjectName(u"jifen")
        self.groupBox_7 = QGroupBox(self.jifen)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 60, 251, 51))
        self.jifen_jifenbianliang = QLineEdit(self.groupBox_7)
        self.jifen_jifenbianliang.setObjectName(u"jifen_jifenbianliang")
        self.jifen_jifenbianliang.setGeometry(QRect(10, 20, 231, 24))
        self.groupBox_8 = QGroupBox(self.jifen)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(400, 60, 121, 51))
        self.jifen_shangxianzhi = QLineEdit(self.groupBox_8)
        self.jifen_shangxianzhi.setObjectName(u"jifen_shangxianzhi")
        self.jifen_shangxianzhi.setEnabled(False)
        self.jifen_shangxianzhi.setGeometry(QRect(10, 20, 101, 24))
        self.groupBox3_2 = QGroupBox(self.jifen)
        self.groupBox3_2.setObjectName(u"groupBox3_2")
        self.groupBox3_2.setGeometry(QRect(10, 250, 771, 131))
        self.jifen_yuanhanshu = QWebEngineView(self.groupBox3_2)
        self.jifen_yuanhanshu.setObjectName(u"jifen_yuanhanshu")
        self.jifen_yuanhanshu.setGeometry(QRect(10, 19, 751, 71))
        self.jifen_yuanhanshu.setUrl(QUrl(u"about:blank"))
        self.jifen_yuanhanshu_lineedit = QLineEdit(self.groupBox3_2)
        self.jifen_yuanhanshu_lineedit.setObjectName(u"jifen_yuanhanshu_lineedit")
        self.jifen_yuanhanshu_lineedit.setGeometry(QRect(10, 100, 751, 21))
        self.groupBox2_2 = QGroupBox(self.jifen)
        self.groupBox2_2.setObjectName(u"groupBox2_2")
        self.groupBox2_2.setGeometry(QRect(10, 110, 771, 131))
        self.jifen_beijihanshu = QWebEngineView(self.groupBox2_2)
        self.jifen_beijihanshu.setObjectName(u"jifen_beijihanshu")
        self.jifen_beijihanshu.setGeometry(QRect(10, 20, 751, 101))
        self.jifen_beijihanshu.setUrl(QUrl(u"about:blank"))
        self.groupBox_11 = QGroupBox(self.jifen)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 390, 771, 131))
        self.jifen_dingjifenzhi = QWebEngineView(self.groupBox_11)
        self.jifen_dingjifenzhi.setObjectName(u"jifen_dingjifenzhi")
        self.jifen_dingjifenzhi.setGeometry(QRect(10, 20, 751, 71))
        self.jifen_dingjifenzhi.setUrl(QUrl(u"about:blank"))
        self.jifen_dingjifenzhi_lineedit = QLineEdit(self.groupBox_11)
        self.jifen_dingjifenzhi_lineedit.setObjectName(u"jifen_dingjifenzhi_lineedit")
        self.jifen_dingjifenzhi_lineedit.setGeometry(QRect(10, 100, 751, 21))
        self.groupBox1_2 = QGroupBox(self.jifen)
        self.groupBox1_2.setObjectName(u"groupBox1_2")
        self.groupBox1_2.setGeometry(QRect(10, 10, 771, 51))
        self.jifen_input = QLineEdit(self.groupBox1_2)
        self.jifen_input.setObjectName(u"jifen_input")
        self.jifen_input.setGeometry(QRect(10, 20, 751, 21))
        self.jifen_jifen_button = QPushButton(self.jifen)
        self.jifen_jifen_button.setObjectName(u"jifen_jifen_button")
        self.jifen_jifen_button.setGeometry(QRect(10, 530, 771, 26))
        self.groupBox_9 = QGroupBox(self.jifen)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(270, 60, 121, 51))
        self.jifen_xiaxianzhi = QLineEdit(self.groupBox_9)
        self.jifen_xiaxianzhi.setObjectName(u"jifen_xiaxianzhi")
        self.jifen_xiaxianzhi.setEnabled(False)
        self.jifen_xiaxianzhi.setGeometry(QRect(10, 20, 101, 24))
        self.jifen_dingjifen = QCheckBox(self.jifen)
        self.jifen_dingjifen.setObjectName(u"jifen_dingjifen")
        self.jifen_dingjifen.setGeometry(QRect(530, 80, 89, 22))
        self.tabWidget.addTab(self.jifen, "")
        self.bianxing = QWidget()
        self.bianxing.setObjectName(u"bianxing")
        self.groupBox_2 = QGroupBox(self.bianxing)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 771, 51))
        self.bianxing_input = QLineEdit(self.groupBox_2)
        self.bianxing_input.setObjectName(u"bianxing_input")
        self.bianxing_input.setGeometry(QRect(10, 20, 751, 21))
        self.bianxing_bianxing_button = QPushButton(self.bianxing)
        self.bianxing_bianxing_button.setObjectName(u"bianxing_bianxing_button")
        self.bianxing_bianxing_button.setGeometry(QRect(10, 530, 771, 26))
        self.groupBox_13 = QGroupBox(self.bianxing)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 60, 771, 51))
        self.bianxing_bianxingfangfa = QComboBox(self.groupBox_13)
        self.bianxing_bianxingfangfa.setObjectName(u"bianxing_bianxingfangfa")
        self.bianxing_bianxingfangfa.setGeometry(QRect(10, 20, 751, 21))
        self.bianxing_bianxingfangfa.setEditable(False)
        self.bianxing_bianxingfangfa.setMaxVisibleItems(13)
        self.groupBox_12 = QGroupBox(self.bianxing)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 330, 771, 191))
        self.bianxing_bianxingshi = QWebEngineView(self.groupBox_12)
        self.bianxing_bianxingshi.setObjectName(u"bianxing_bianxingshi")
        self.bianxing_bianxingshi.setGeometry(QRect(10, 20, 751, 131))
        self.bianxing_bianxingshi.setUrl(QUrl(u"about:blank"))
        self.bianxing_bianxingshi_lineedit = QLineEdit(self.groupBox_12)
        self.bianxing_bianxingshi_lineedit.setObjectName(u"bianxing_bianxingshi_lineedit")
        self.bianxing_bianxingshi_lineedit.setGeometry(QRect(10, 160, 751, 21))
        self.groupBox_16 = QGroupBox(self.bianxing)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(10, 160, 771, 161))
        self.bianxing_yuanshi = QWebEngineView(self.groupBox_16)
        self.bianxing_yuanshi.setObjectName(u"bianxing_yuanshi")
        self.bianxing_yuanshi.setGeometry(QRect(10, 20, 751, 131))
        self.bianxing_yuanshi.setUrl(QUrl(u"about:blank"))
        self.groupBox_10 = QGroupBox(self.bianxing)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 110, 771, 51))
        self.label = QLabel(self.groupBox_10)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 81, 18))
        self.bianxing_zhuyuanfuhao = QLineEdit(self.groupBox_10)
        self.bianxing_zhuyuanfuhao.setObjectName(u"bianxing_zhuyuanfuhao")
        self.bianxing_zhuyuanfuhao.setEnabled(False)
        self.bianxing_zhuyuanfuhao.setGeometry(QRect(100, 20, 51, 21))
        self.label_2 = QLabel(self.groupBox_10)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(170, 20, 71, 20))
        self.bianxing_huanyuanfuhao = QLineEdit(self.groupBox_10)
        self.bianxing_huanyuanfuhao.setObjectName(u"bianxing_huanyuanfuhao")
        self.bianxing_huanyuanfuhao.setEnabled(False)
        self.bianxing_huanyuanfuhao.setGeometry(QRect(250, 20, 51, 21))
        self.label_3 = QLabel(self.groupBox_10)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(310, 20, 16, 18))
        self.bianxing_huanyuanshi = QLineEdit(self.groupBox_10)
        self.bianxing_huanyuanshi.setObjectName(u"bianxing_huanyuanshi")
        self.bianxing_huanyuanshi.setEnabled(False)
        self.bianxing_huanyuanshi.setGeometry(QRect(330, 20, 431, 21))
        self.tabWidget.addTab(self.bianxing, "")
        self.fangcheng = QWidget()
        self.fangcheng.setObjectName(u"fangcheng")
        self.groupBox_14 = QGroupBox(self.fangcheng)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 10, 771, 80))
        self.fangcheng_zuoshi = QLineEdit(self.groupBox_14)
        self.fangcheng_zuoshi.setObjectName(u"fangcheng_zuoshi")
        self.fangcheng_zuoshi.setGeometry(QRect(10, 20, 751, 21))
        self.label_4 = QLabel(self.groupBox_14)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 16, 18))
        self.fangcheng_youshi = QLineEdit(self.groupBox_14)
        self.fangcheng_youshi.setObjectName(u"fangcheng_youshi")
        self.fangcheng_youshi.setGeometry(QRect(30, 50, 731, 21))
        self.groupBox_15 = QGroupBox(self.fangcheng)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 90, 771, 51))
        self.label_5 = QLabel(self.groupBox_15)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 81, 18))
        self.fangcheng_zhuyuanfuhao = QLineEdit(self.groupBox_15)
        self.fangcheng_zhuyuanfuhao.setObjectName(u"fangcheng_zhuyuanfuhao")
        self.fangcheng_zhuyuanfuhao.setGeometry(QRect(100, 20, 51, 21))
        self.label_6 = QLabel(self.groupBox_15)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(170, 20, 111, 18))
        self.fangcheng_quzhifanwei = QLineEdit(self.groupBox_15)
        self.fangcheng_quzhifanwei.setObjectName(u"fangcheng_quzhifanwei")
        self.fangcheng_quzhifanwei.setGeometry(QRect(290, 20, 471, 21))
        self.groupBox_17 = QGroupBox(self.fangcheng)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(10, 320, 771, 201))
        self.fangcheng_jieji = QWebEngineView(self.groupBox_17)
        self.fangcheng_jieji.setObjectName(u"fangcheng_jieji")
        self.fangcheng_jieji.setGeometry(QRect(10, 20, 751, 141))
        self.fangcheng_jieji.setUrl(QUrl(u"about:blank"))
        self.fangcheng_jieji_lineedit = QLineEdit(self.groupBox_17)
        self.fangcheng_jieji_lineedit.setObjectName(u"fangcheng_jieji_lineedit")
        self.fangcheng_jieji_lineedit.setGeometry(QRect(10, 170, 751, 21))
        self.fangcheng_qiujie = QPushButton(self.fangcheng)
        self.fangcheng_qiujie.setObjectName(u"fangcheng_qiujie")
        self.fangcheng_qiujie.setGeometry(QRect(10, 530, 771, 26))
        self.groupBox_18 = QGroupBox(self.fangcheng)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 150, 771, 171))
        self.fangcheng_yuanfangcheng = QWebEngineView(self.groupBox_18)
        self.fangcheng_yuanfangcheng.setObjectName(u"fangcheng_yuanfangcheng")
        self.fangcheng_yuanfangcheng.setGeometry(QRect(10, 20, 751, 141))
        self.fangcheng_yuanfangcheng.setUrl(QUrl(u"about:blank"))
        self.tabWidget.addTab(self.fangcheng, "")
        self.budengshi = QWidget()
        self.budengshi.setObjectName(u"budengshi")
        self.groupBox_37 = QGroupBox(self.budengshi)
        self.groupBox_37.setObjectName(u"groupBox_37")
        self.groupBox_37.setGeometry(QRect(10, 150, 771, 171))
        self.budengshi_yuanshi = QWebEngineView(self.groupBox_37)
        self.budengshi_yuanshi.setObjectName(u"budengshi_yuanshi")
        self.budengshi_yuanshi.setGeometry(QRect(10, 20, 751, 141))
        self.budengshi_yuanshi.setUrl(QUrl(u"about:blank"))
        self.budengshi_qiujie = QPushButton(self.budengshi)
        self.budengshi_qiujie.setObjectName(u"budengshi_qiujie")
        self.budengshi_qiujie.setGeometry(QRect(10, 530, 771, 26))
        self.groupBox_38 = QGroupBox(self.budengshi)
        self.groupBox_38.setObjectName(u"groupBox_38")
        self.groupBox_38.setGeometry(QRect(10, 10, 771, 80))
        self.budengshi_zuoshi = QLineEdit(self.groupBox_38)
        self.budengshi_zuoshi.setObjectName(u"budengshi_zuoshi")
        self.budengshi_zuoshi.setGeometry(QRect(10, 20, 751, 21))
        self.budengshi_youshi = QLineEdit(self.groupBox_38)
        self.budengshi_youshi.setObjectName(u"budengshi_youshi")
        self.budengshi_youshi.setGeometry(QRect(90, 50, 671, 21))
        self.budengshi_budenghao = QComboBox(self.groupBox_38)
        self.budengshi_budenghao.setObjectName(u"budengshi_budenghao")
        self.budengshi_budenghao.setGeometry(QRect(10, 50, 71, 21))
        self.groupBox_39 = QGroupBox(self.budengshi)
        self.groupBox_39.setObjectName(u"groupBox_39")
        self.groupBox_39.setGeometry(QRect(10, 90, 771, 51))
        self.label_14 = QLabel(self.groupBox_39)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 20, 81, 18))
        self.budengshi_zhuyuanfuhao = QLineEdit(self.groupBox_39)
        self.budengshi_zhuyuanfuhao.setObjectName(u"budengshi_zhuyuanfuhao")
        self.budengshi_zhuyuanfuhao.setGeometry(QRect(100, 20, 51, 21))
        self.label_15 = QLabel(self.groupBox_39)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(170, 20, 111, 18))
        self.budengshi_quzhifanwei = QLineEdit(self.groupBox_39)
        self.budengshi_quzhifanwei.setObjectName(u"budengshi_quzhifanwei")
        self.budengshi_quzhifanwei.setGeometry(QRect(290, 20, 471, 21))
        self.groupBox_40 = QGroupBox(self.budengshi)
        self.groupBox_40.setObjectName(u"groupBox_40")
        self.groupBox_40.setGeometry(QRect(10, 320, 771, 201))
        self.budengshi_jieji = QWebEngineView(self.groupBox_40)
        self.budengshi_jieji.setObjectName(u"budengshi_jieji")
        self.budengshi_jieji.setGeometry(QRect(10, 20, 751, 141))
        self.budengshi_jieji.setUrl(QUrl(u"about:blank"))
        self.budengshi_jieji_lineedit = QLineEdit(self.groupBox_40)
        self.budengshi_jieji_lineedit.setObjectName(u"budengshi_jieji_lineedit")
        self.budengshi_jieji_lineedit.setGeometry(QRect(10, 170, 751, 21))
        self.tabWidget.addTab(self.budengshi, "")
        self.help = QWidget()
        self.help.setObjectName(u"help")
        self.webEngineView = QWebEngineView(self.help)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setGeometry(QRect(0, 0, 791, 571))
        self.webEngineView.setUrl(QUrl(u"file:///F:/Anaconda3/envs/PyQt/Projects/SymPy/CalculusCalculator/v1.3/src/help.html"))
        self.tabWidget.addTab(self.help, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.dingyi_hanshushuxing.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u5fae\u79ef\u5206\u8ba1\u7b97\u5668v1.3", None))
        self.shouye_welcome.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u6b22\u8fce\u4f7f\u7528\u5fae\u79ef\u5206\u8ba1\u7b97\u5668v1.3\uff01</p><p>Author: Li Mingkang</p><p>Contributor: CuberAHZ</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shouye), QCoreApplication.translate("MainWindow", u"\u9996\u9875", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u5217\u8868", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u7f16\u8f91\u533a", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u540d\u79f0\uff1a", None))
        self.dingyi_mingcheng.setText(QCoreApplication.translate("MainWindow", u"f", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u8868\u8fbe\u5f0f\uff1a", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u5b9a\u4e49\u57df\uff1a", None))
        self.dingyi_dingyiyu.setText(QCoreApplication.translate("MainWindow", u"Reals", None))
        self.dingyi_shanchu.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.dingyi_baocun.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u81ea\u53d8\u91cf\uff1a", None))
        self.dingyi_zibianliang.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u5c5e\u6027\u533a", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("MainWindow", u"\u51fd\u6570\u6c42\u503c", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u53d8\u91cf\u503c\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dingyi), QCoreApplication.translate("MainWindow", u"\u5b9a\u4e49", None))
        self.groupBox1.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u8868\u8fbe\u5f0f", None))
        self.groupBox2.setTitle(QCoreApplication.translate("MainWindow", u"\u539f\u51fd\u6570", None))
        self.groupBox3.setTitle(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fd\u6570", None))
        self.qiudao_qiudao_button.setText(QCoreApplication.translate("MainWindow", u"\u6c42\u5bfc", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u81ea\u53d8\u91cf", None))
        self.qiudao_zibianliang.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.qiudao_yinhanshu.setText(QCoreApplication.translate("MainWindow", u"\u9690\u51fd\u6570", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u6c42\u5bfc\u6b21\u6570", None))
        self.qiudao_qiudaocishu.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u56e0\u53d8\u91cf(\u4ec5\u9690\u51fd\u6570)", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u5bfc\u6570\u503c", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u81ea\u53d8\u91cf\u503c", None))
        self.qiudao_qiuchujutizhi.setText(QCoreApplication.translate("MainWindow", u"\u6c42\u51fa\u5177\u4f53\u503c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.qiudao), QCoreApplication.translate("MainWindow", u"\u6c42\u5bfc", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\u79ef\u5206\u53d8\u91cf", None))
        self.jifen_jifenbianliang.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"\u4e0a\u9650\u503c", None))
        self.groupBox3_2.setTitle(QCoreApplication.translate("MainWindow", u"\u539f\u51fd\u6570", None))
        self.groupBox2_2.setTitle(QCoreApplication.translate("MainWindow", u"\u88ab\u79ef\u51fd\u6570", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"\u5b9a\u79ef\u5206\u503c", None))
        self.groupBox1_2.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u8868\u8fbe\u5f0f", None))
        self.jifen_jifen_button.setText(QCoreApplication.translate("MainWindow", u"\u79ef\u5206", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"\u4e0b\u9650\u503c", None))
        self.jifen_dingjifen.setText(QCoreApplication.translate("MainWindow", u"\u5b9a\u79ef\u5206", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jifen), QCoreApplication.translate("MainWindow", u"\u79ef\u5206", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u8868\u8fbe\u5f0f", None))
        self.bianxing_bianxing_button.setText(QCoreApplication.translate("MainWindow", u"\u53d8\u5f62", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"\u53d8\u5f62\u65b9\u6cd5", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"\u53d8\u5f62\u5f0f", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("MainWindow", u"\u539f\u5f0f", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u9879", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u5143\u7b26\u53f7\uff1a", None))
        self.bianxing_zhuyuanfuhao.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u6362\u5143\u7b26\u53f7\uff1a", None))
        self.bianxing_huanyuanfuhao.setText(QCoreApplication.translate("MainWindow", u"t", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.bianxing_huanyuanshi.setText(QCoreApplication.translate("MainWindow", u"x+1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bianxing), QCoreApplication.translate("MainWindow", u"\u53d8\u5f62", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u65b9\u7a0b", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.fangcheng_youshi.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u9879", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u5143\u7b26\u53f7\uff1a", None))
        self.fangcheng_zhuyuanfuhao.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u5143\u53d6\u503c\u8303\u56f4\uff1a", None))
        self.fangcheng_quzhifanwei.setText(QCoreApplication.translate("MainWindow", u"Reals", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"\u89e3\u96c6", None))
        self.fangcheng_qiujie.setText(QCoreApplication.translate("MainWindow", u"\u6c42\u89e3", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("MainWindow", u"\u539f\u65b9\u7a0b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fangcheng), QCoreApplication.translate("MainWindow", u"\u65b9\u7a0b", None))
        self.groupBox_37.setTitle(QCoreApplication.translate("MainWindow", u"\u539f\u4e0d\u7b49\u5f0f", None))
        self.budengshi_qiujie.setText(QCoreApplication.translate("MainWindow", u"\u6c42\u89e3", None))
        self.groupBox_38.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u4e0d\u7b49\u5f0f", None))
        self.budengshi_youshi.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_39.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u9879", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u5143\u7b26\u53f7\uff1a", None))
        self.budengshi_zhuyuanfuhao.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u5143\u53d6\u503c\u8303\u56f4\uff1a", None))
        self.budengshi_quzhifanwei.setText(QCoreApplication.translate("MainWindow", u"Reals", None))
        self.groupBox_40.setTitle(QCoreApplication.translate("MainWindow", u"\u89e3\u96c6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.budengshi), QCoreApplication.translate("MainWindow", u"\u4e0d\u7b49\u5f0f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.help), QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
    # retranslateUi

