# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainIYlUKk.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QTabWidget, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        icon = QIcon()
        icon.addFile(u":/favicon.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/favicon.ico", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.actionshouye = QAction(MainWindow)
        self.actionshouye.setObjectName(u"actionshouye")
        self.actionhelp = QAction(MainWindow)
        self.actionhelp.setObjectName(u"actionhelp")
        self.actiongithub = QAction(MainWindow)
        self.actiongithub.setObjectName(u"actiongithub")
        self.actionwebsite = QAction(MainWindow)
        self.actionwebsite.setObjectName(u"actionwebsite")
        self.actionsaveas = QAction(MainWindow)
        self.actionsaveas.setObjectName(u"actionsaveas")
        self.actionopen = QAction(MainWindow)
        self.actionopen.setObjectName(u"actionopen")
        self.actionexit = QAction(MainWindow)
        self.actionexit.setObjectName(u"actionexit")
        self.actionqiudao = QAction(MainWindow)
        self.actionqiudao.setObjectName(u"actionqiudao")
        self.actionjifen = QAction(MainWindow)
        self.actionjifen.setObjectName(u"actionjifen")
        self.actionfangcheng = QAction(MainWindow)
        self.actionfangcheng.setObjectName(u"actionfangcheng")
        self.actionfangchengzu = QAction(MainWindow)
        self.actionfangchengzu.setObjectName(u"actionfangchengzu")
        self.actionbudengshi = QAction(MainWindow)
        self.actionbudengshi.setObjectName(u"actionbudengshi")
        self.actionbudengshizu = QAction(MainWindow)
        self.actionbudengshizu.setObjectName(u"actionbudengshizu")
        self.actionbianxing = QAction(MainWindow)
        self.actionbianxing.setObjectName(u"actionbianxing")
        self.actiondingyi = QAction(MainWindow)
        self.actiondingyi.setObjectName(u"actiondingyi")
        self.actiondingyixiangliang = QAction(MainWindow)
        self.actiondingyixiangliang.setObjectName(u"actiondingyixiangliang")
        self.actionhuitu_hanshu = QAction(MainWindow)
        self.actionhuitu_hanshu.setObjectName(u"actionhuitu_hanshu")
        self.actionhuitu_pingmianjihe = QAction(MainWindow)
        self.actionhuitu_pingmianjihe.setObjectName(u"actionhuitu_pingmianjihe")
        self.actionhuitu_litijihe = QAction(MainWindow)
        self.actionhuitu_litijihe.setObjectName(u"actionhuitu_litijihe")
        self.actionjiesanjiaoxing = QAction(MainWindow)
        self.actionjiesanjiaoxing.setObjectName(u"actionjiesanjiaoxing")
        self.actiondingyi_pj = QAction(MainWindow)
        self.actiondingyi_pj.setObjectName(u"actiondingyi_pj")
        self.actiondingyi_lj = QAction(MainWindow)
        self.actiondingyi_lj.setObjectName(u"actiondingyi_lj")
        self.actionjisuan = QAction(MainWindow)
        self.actionjisuan.setObjectName(u"actionjisuan")
        self.actionpjjisuan = QAction(MainWindow)
        self.actionpjjisuan.setObjectName(u"actionpjjisuan")
        self.actionljjisuan = QAction(MainWindow)
        self.actionljjisuan.setObjectName(u"actionljjisuan")
        self.actionlight = QAction(MainWindow)
        self.actionlight.setObjectName(u"actionlight")
        self.actiondark = QAction(MainWindow)
        self.actiondark.setObjectName(u"actiondark")
        self.actionshezhi = QAction(MainWindow)
        self.actionshezhi.setObjectName(u"actionshezhi")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 25))
        self.functions = QMenu(self.menubar)
        self.functions.setObjectName(u"functions")
        self.calculus = QMenu(self.functions)
        self.calculus.setObjectName(u"calculus")
        self.dingyi = QMenu(self.functions)
        self.dingyi.setObjectName(u"dingyi")
        self.solve = QMenu(self.functions)
        self.solve.setObjectName(u"solve")
        self.daishushi = QMenu(self.functions)
        self.daishushi.setObjectName(u"daishushi")
        self.huitu = QMenu(self.functions)
        self.huitu.setObjectName(u"huitu")
        self.jisuan = QMenu(self.functions)
        self.jisuan.setObjectName(u"jisuan")
        self.about = QMenu(self.menubar)
        self.about.setObjectName(u"about")
        self.file = QMenu(self.menubar)
        self.file.setObjectName(u"file")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.functions.menuAction())
        self.menubar.addAction(self.about.menuAction())
        self.functions.addAction(self.actionshouye)
        self.functions.addAction(self.dingyi.menuAction())
        self.functions.addAction(self.calculus.menuAction())
        self.functions.addAction(self.daishushi.menuAction())
        self.functions.addAction(self.jisuan.menuAction())
        self.functions.addAction(self.solve.menuAction())
        self.functions.addAction(self.huitu.menuAction())
        self.functions.addAction(self.actionjiesanjiaoxing)
        self.calculus.addAction(self.actionqiudao)
        self.calculus.addAction(self.actionjifen)
        self.dingyi.addAction(self.actiondingyi)
        self.dingyi.addAction(self.actiondingyixiangliang)
        self.dingyi.addAction(self.actiondingyi_pj)
        self.dingyi.addAction(self.actiondingyi_lj)
        self.solve.addAction(self.actionfangcheng)
        self.solve.addAction(self.actionfangchengzu)
        self.solve.addAction(self.actionbudengshi)
        self.solve.addAction(self.actionbudengshizu)
        self.daishushi.addAction(self.actionbianxing)
        self.huitu.addAction(self.actionhuitu_hanshu)
        self.huitu.addAction(self.actionhuitu_pingmianjihe)
        self.huitu.addAction(self.actionhuitu_litijihe)
        self.jisuan.addAction(self.actionjisuan)
        self.jisuan.addAction(self.actionpjjisuan)
        self.jisuan.addAction(self.actionljjisuan)
        self.about.addAction(self.actiongithub)
        self.about.addAction(self.actionwebsite)
        self.about.addAction(self.actionhelp)
        self.file.addAction(self.actionsaveas)
        self.file.addAction(self.actionopen)
        self.file.addAction(self.actionshezhi)
        self.file.addAction(self.actionexit)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CalculusCalculator", None))
        self.actionshouye.setText(QCoreApplication.translate("MainWindow", u"\u9996\u9875", None))
        self.actionhelp.setText(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.actiongithub.setText(QCoreApplication.translate("MainWindow", u"Github\u94fe\u63a5", None))
        self.actionwebsite.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u9875\u7248", None))
        self.actionsaveas.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a", None))
        self.actionopen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.actionexit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.actionqiudao.setText(QCoreApplication.translate("MainWindow", u"\u6c42\u5bfc", None))
        self.actionjifen.setText(QCoreApplication.translate("MainWindow", u"\u79ef\u5206", None))
        self.actionfangcheng.setText(QCoreApplication.translate("MainWindow", u"\u65b9\u7a0b", None))
        self.actionfangchengzu.setText(QCoreApplication.translate("MainWindow", u"\u65b9\u7a0b\u7ec4", None))
        self.actionbudengshi.setText(QCoreApplication.translate("MainWindow", u"\u4e0d\u7b49\u5f0f", None))
        self.actionbudengshizu.setText(QCoreApplication.translate("MainWindow", u"\u4e0d\u7b49\u5f0f\u7ec4", None))
        self.actionbianxing.setText(QCoreApplication.translate("MainWindow", u"\u53d8\u5f62", None))
        self.actiondingyi.setText(QCoreApplication.translate("MainWindow", u"\u51fd\u6570", None))
        self.actiondingyixiangliang.setText(QCoreApplication.translate("MainWindow", u"\u5411\u91cf", None))
        self.actionhuitu_hanshu.setText(QCoreApplication.translate("MainWindow", u"\u51fd\u6570", None))
        self.actionhuitu_pingmianjihe.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u9762\u51e0\u4f55", None))
        self.actionhuitu_litijihe.setText(QCoreApplication.translate("MainWindow", u"\u7acb\u4f53\u51e0\u4f55", None))
        self.actionjiesanjiaoxing.setText(QCoreApplication.translate("MainWindow", u"\u89e3\u4e09\u89d2\u5f62", None))
        self.actiondingyi_pj.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u9762\u51e0\u4f55", None))
        self.actiondingyi_lj.setText(QCoreApplication.translate("MainWindow", u"\u7acb\u4f53\u51e0\u4f55", None))
        self.actionjisuan.setText(QCoreApplication.translate("MainWindow", u"\u4ee3\u6570\u5f0f\u8ba1\u7b97", None))
        self.actionpjjisuan.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u9762\u51e0\u4f55\u8ba1\u7b97", None))
        self.actionljjisuan.setText(QCoreApplication.translate("MainWindow", u"\u7acb\u4f53\u51e0\u4f55\u8ba1\u7b97", None))
        self.actionlight.setText(QCoreApplication.translate("MainWindow", u"\u6d45\u8272", None))
        self.actiondark.setText(QCoreApplication.translate("MainWindow", u"\u6df1\u8272", None))
        self.actionshezhi.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.functions.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd", None))
        self.calculus.setTitle(QCoreApplication.translate("MainWindow", u"\u5fae\u79ef\u5206", None))
        self.dingyi.setTitle(QCoreApplication.translate("MainWindow", u"\u5b9a\u4e49", None))
        self.solve.setTitle(QCoreApplication.translate("MainWindow", u"\u6c42\u89e3", None))
        self.daishushi.setTitle(QCoreApplication.translate("MainWindow", u"\u4ee3\u6570\u5f0f", None))
        self.huitu.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe", None))
        self.jisuan.setTitle(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97", None))
        self.about.setTitle(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.file.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
    # retranslateUi

